services:
  - type: web
    name: qr-attendance-system
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: gunicorn render_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_SECRET_CODE
        value: "23456"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: qr-attendance-db
          property: connectionString

  - type: pserv
    name: qr-attendance-db
    databaseName: qra_attendance
    user: qr_user
